version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  consumer:
    build: .
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_GROUP_ID=enterprise_consumer_group
      - DATABASE_URL=sqlite:///data/enterprise.db
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/consumer.log
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

  load-test:
    build: .
    command: python -m pytest tests/load_tests/ -v
    depends_on:
      - kafka
    environment:
      - APP_ENV=test
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_GROUP_ID=load_test_group
      - DATABASE_URL=sqlite:///data/enterprise.db
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/load_test.log
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

volumes:
  postgres_data: 